version: '3'
services:
  app:
    build: .
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - TOPIC=${TOPIC}
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - MODEL=${MODEL}
      - OUTPUT_TOPIC=${OUTPUT_TOPIC}
    volumes:
      - ./logs:/usr/src/app/logs  # For winston logs
